# Generated by Django 4.2.5 on 2023-09-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=14)),
                ('EMI_no', models.IntegerField()),
                ('model_id_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.student')),
            ],
        ),
    ]
