# Generated by Django 4.2.5 on 2023-09-22 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='model_id_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.item'),
        ),
    ]
